### ISSUE TITLE
Cannot use UTF-8 strings

### ISSUE THREAD

**Issue by W4RH4WK** [SeTeM/pync#23]
i just encountered an issue when passing a translated string containing non-ascii characters.

```
Traceback (most recent call last):
  [...]
  File "/Users/user/Desktop/MyApp/virt/lib/python2.7/site-packages/pync/TerminalNotifier.py", line 74, in notify
    return self.execute(args)
  File "/Users/user/Desktop/MyApp/virt/lib/python2.7/site-packages/pync/TerminalNotifier.py", line 77, in execute
    args = [str(arg) for arg in args]
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 39: ordinal not in range(128)
```

Using `unicode(arg)` instead of `str(arg)` should fix this.

**Comment by daxeel** [comment]
You can also use this
```py
string.encode('utf-8')
```

**Comment by daxeel** [comment]
Update pync from github. We now fixed it. :)
