### ISSUE TITLE
is pync compatible with OSX El Capitan?

### ISSUE THREAD

**Issue by skyebend** [SeTeM/pync#27]
I'm having trouble getting pync to install.  Is this some sort of SIP issue with El Capitan, or am I just doing something dumb?

```
sudo -H pip install pync
Collecting pync
  Using cached pync-1.6.1.tar.gz
Collecting python-dateutil>=2.0 (from pync)
  Using cached python_dateutil-2.5.3-py2.py3-none-any.whl
Collecting six>=1.5 (from python-dateutil>=2.0->pync)
  Using cached six-1.10.0-py2.py3-none-any.whl
Installing collected packages: six, python-dateutil, pync
  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_set.py", line 736, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_install.py", line 742, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-wlYSeB-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'
```

**Comment by pi314** [comment]
I just installed `pync` on my OSX El Capitan, works fine (Python3).

**Comment by SeTeM** [comment]
I don't have El Capitan, but it works on my Sierra

**Comment by pi314** [comment]
Can you try install it in virtualenv without `sudo` ? If it works, maybe the problem is not related to pync.

**Comment by maxkrivich** [comment]
@skyebend it looks like the problem on pip side  [#3165](https://github.com/pypa/pip/issues/3165). You can try this [`solution`](https://stackoverflow.com/questions/31900008/oserror-errno-1-operation-not-permitted-when-installing-scrapy-in-osx-10-11?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa).
