### ISSUE TITLE
Installation error with Python3

### ISSUE THREAD

**Issue by romanpeters** [SeTeM/pync#31]
Tried a few different methods, but every time I try to install the package with Python 3, I get the following error:

```
pip3 install pync
Collecting pync
  Using cached pync-1.6.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/64/vnv3jxhs47gbzbw3wcjf0hyw0000gn/T/pip-build-152ozf45/pync/setup.py", line 10, in <module>
        file_contents.append(open(path).read())
      File "/Users/romanpeters/Projects/Python/Scripts/venv/bin/../lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 589: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/64/vnv3jxhs47gbzbw3wcjf0hyw0000gn/T/pip-build-152ozf45/pync/

```

Python 2 still seems to work.

**Comment by shadow-identity** [comment]
@romanpeters Hi, 
Please try 2.0.0 version, bug should be fixed.
