### ISSUE TITLE
FileNotFoundError during install of 2.0.0

### ISSUE THREAD

**Issue by jacebrowning** [SeTeM/pync#34]
```
$ pip install pync
Collecting pync
  Using cached pync-2.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/h1/2b6gts3x37zcnj5khyv8y5180000gn/T/pip-build-8sa_tyyb/pync/setup.py", line 10, in <module>
        file_contents.append(open(path).read())
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/h1/2b6gts3x37zcnj5khyv8y5180000gn/T/pip-build-8sa_tyyb/pync/README.md'
```

**Comment by maxkrivich** [comment]
@jacebrowning fixed
