### ISSUE TITLE
list() method raises AttributeError

### ISSUE THREAD

**Issue by manjiki** [SeTeM/pync#35]
When trying to get a list of notifications sent, we get an AttributeError

```>>> from pync import Notifier
>>> Notifier.list()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pync/TerminalNotifier.py", line 107, in list
    output = self.execute(["-list", group]).communicate()[0]
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pync/TerminalNotifier.py", line 79, in execute
    if self.wait:
AttributeError: 'TerminalNotifier' object has no attribute 'wait'```

**Comment by maxkrivich** [comment]
@manjiki fixed
